'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class custom_order
    Public Property id As Integer
    Public Property category_id As Integer
    Public Property size_description As String
    Public Property description As String
    Public Property quantity As Integer
    Public Property note As String
    Public Property delivery_date As Date
    Public Property address As String
    Public Property recipient_full_name As String
    Public Property phone As String
    Public Property status As Nullable(Of Boolean)
    Public Property user_id As Nullable(Of Integer)
    Public Property register_time As Nullable(Of Date)
    Public Property confirm As Nullable(Of Boolean)
    Public Property img_product As String
    Public Property total_price As Nullable(Of Decimal)

End Class
