'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class custom_order_notification
    Public Property id As Integer
    Public Property user_id As Integer
    Public Property order_id As Integer
    Public Property content_notification As String
    Public Property status As Boolean
    Public Property register_date As Nullable(Of Date)
    Public Property is_custom_order As Nullable(Of Boolean)

End Class
