'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class DBNetEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=DBNetEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property carts() As DbSet(Of cart)
    Public Overridable Property cart_detail() As DbSet(Of cart_detail)
    Public Overridable Property categories() As DbSet(Of category)
    Public Overridable Property custom_order() As DbSet(Of custom_order)
    Public Overridable Property custom_order_notification() As DbSet(Of custom_order_notification)
    Public Overridable Property deliveries() As DbSet(Of delivery)
    Public Overridable Property favorites() As DbSet(Of favorite)
    Public Overridable Property orders() As DbSet(Of order)
    Public Overridable Property order_detail() As DbSet(Of order_detail)
    Public Overridable Property products() As DbSet(Of product)
    Public Overridable Property purchased_product() As DbSet(Of purchased_product)
    Public Overridable Property rates() As DbSet(Of rate)
    Public Overridable Property users() As DbSet(Of user)
    Public Overridable Property user_info() As DbSet(Of user_info)

End Class
