'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class notification
    Public Property id As Integer
    Public Property type_of_notification As Integer
    Public Property type_of_notification_id As Integer
    Public Property user_id As Integer
    Public Property content_notification As String
    Public Property status As Boolean
    Public Property register_time As Date

End Class
