'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class order
    Public Property id As Integer
    Public Property user_id As Integer
    Public Property total_price As Decimal
    Public Property quantity As Integer
    Public Property register_time As Date
    Public Property status As Boolean
    Public Property delivery_id As Nullable(Of Integer)

End Class
