'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class post
    Public Property id As Integer
    Public Property title As String
    Public Property register_date As Date
    Public Property ingredient As String
    Public Property process As String
    Public Property image As String
    Public Property post_content As String

End Class
