'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class purchased_order_detail
    Public Property id As Integer
    Public Property ingredient_name As String
    Public Property quantity As Integer
    Public Property ingredient_category_id As Integer
    Public Property price As String
    Public Property purchased_order_id As Integer
    Public Property ingredient_id As Nullable(Of Integer)

End Class
