'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class rate
    Public Property id As Integer
    Public Property star As Integer
    Public Property comment As String
    Public Property user_id As Integer
    Public Property product_id As Integer
    Public Property register_time As Date

End Class
